name: seizhiptv
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


flutter_native_splash:
  color: "#101010"
  image: "assets/icons/Vector.png"
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
  min_sdk_android: 26
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17
  easy_localization: ^3.0.7+1
  page_transition: ^2.2.1
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  file_picker: ^10.1.2
  cached_network_image: ^3.4.1
  persistent_bottom_nav_bar: ^6.2.1
  google_sign_in: ^6.3.0
  google_sign_in_ios: ^5.9.0
  http: ^1.3.0
  firebase_auth: ^5.5.2
  fluttertoast: ^8.2.12
  firebase_core: ^3.13.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  cloud_firestore: ^5.6.6
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  flutter_vlc_player: ^7.4.3
  timeago: ^3.7.0
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lang/
    - .env
    